"""Internal message model.

Claude Code wraps Anthropic API messages in an internal envelope carrying a
uuid, timestamps, and orchestration metadata (compact boundaries, source tool
attribution). We do the same over Azure OpenAI chat-completion shapes: the
envelope is ours, `to_openai()` produces the wire format.
"""

from __future__ import annotations

import time
import uuid as _uuid
from dataclasses import dataclass, field
from typing import Any, Literal

Role = Literal["system", "user", "assistant", "tool"]


@dataclass
class ToolCall:
    id: str
    name: str
    arguments: str  # raw JSON string, as streamed from the model

    def to_openai(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "type": "function",
            "function": {"name": self.name, "arguments": self.arguments},
        }


@dataclass
class Message:
    role: Role
    content: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)
    tool_call_id: str | None = None  # set on role="tool" results
    is_error: bool = False
    uuid: str = field(default_factory=lambda: str(_uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)
    # Orchestration metadata invisible to the model:
    #   compact_boundary: message is an autocompact summary boundary
    #   microcompacted:   tool result content was stubbed
    #   agent_id:         produced inside a subagent sidechain
    #   synthetic:        generated by the loop (interruption results, etc.)
    meta: dict[str, Any] = field(default_factory=dict)

    def to_openai(self) -> dict[str, Any]:
        msg: dict[str, Any] = {"role": self.role}
        if self.role == "tool":
            msg["tool_call_id"] = self.tool_call_id
            msg["content"] = self.content or ""
            return msg
        msg["content"] = self.content or ""
        if self.tool_calls:
            msg["tool_calls"] = [tc.to_openai() for tc in self.tool_calls]
        return msg

    def to_record(self) -> dict[str, Any]:
        """JSONL transcript record (sessionStorage analog)."""
        return {
            "uuid": self.uuid,
            "timestamp": self.timestamp,
            "role": self.role,
            "content": self.content,
            "tool_calls": [tc.to_openai() for tc in self.tool_calls],
            "tool_call_id": self.tool_call_id,
            "is_error": self.is_error,
            "meta": self.meta,
        }

    @classmethod
    def from_record(cls, rec: dict[str, Any]) -> "Message":
        return cls(
            role=rec["role"],
            content=rec.get("content"),
            tool_calls=[
                ToolCall(
                    id=tc["id"],
                    name=tc["function"]["name"],
                    arguments=tc["function"]["arguments"],
                )
                for tc in rec.get("tool_calls") or []
            ],
            tool_call_id=rec.get("tool_call_id"),
            is_error=rec.get("is_error", False),
            uuid=rec.get("uuid", str(_uuid.uuid4())),
            timestamp=rec.get("timestamp", time.time()),
            meta=rec.get("meta") or {},
        )


def user_message(content: str, **meta: Any) -> Message:
    return Message(role="user", content=content, meta=meta)


def system_message(content: str, **meta: Any) -> Message:
    return Message(role="system", content=content, meta=meta)


def tool_result_message(
    tool_call_id: str, content: str, *, is_error: bool = False, **meta: Any
) -> Message:
    return Message(
        role="tool",
        content=content,
        tool_call_id=tool_call_id,
        is_error=is_error,
        meta=meta,
    )


def compact_boundary_message(summary: str) -> Message:
    """The autocompact boundary. Everything before it is invisible to the
    model on subsequent iterations (getMessagesAfterCompactBoundary analog)."""
    return Message(
        role="user",
        content=(
            "The conversation history above was compacted. Summary of the "
            f"session so far:\n\n{summary}"
        ),
        meta={"compact_boundary": True},
    )


def messages_after_compact_boundary(messages: list[Message]) -> list[Message]:
    for i in range(len(messages) - 1, -1, -1):
        if messages[i].meta.get("compact_boundary"):
            return messages[i:]
    return messages
