"""A standalone pipeline runtime. Generated by Compass — no Compass required.

This file is copied verbatim into an exported package. It has no third-party
dependencies and no imports from Compass, because the whole point is that it
runs somewhere Compass is not.

It is deliberately a *second* implementation of the walk rather than a shared
one. Compass's engine is async, persists every step to a store, resolves
credentials from a secret backend and can park a run for hours waiting on a
person. None of that belongs in a library you drop into another application.
What has to match is the semantics — edge conditions, fan-out, retries,
expressions — and `scripts/check_export.py` runs both against the same graph
to prove they agree.

Using it:

    from my_pipeline import Pipeline

    p = Pipeline()
    p.register("tool.bash", my_shell_runner)   # supply what Compass stubbed
    result = p.run({"since": "2026-01-01"})

    result.status          # "done" | "failed"
    result.output("send")  # a node's data
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass, field
from typing import Any, Callable

__all__ = ["Pipeline", "RunResult", "NodeResult", "PipelineError", "MissingHandler"]


class PipelineError(Exception):
    """The pipeline could not run, or a node failed with no error branch."""


class MissingHandler(PipelineError):
    """A node type has no implementation here, and the host supplied none.

    Raised rather than skipped on purpose. A pipeline that quietly omits the
    step that sends the email is worse than one that refuses to start, because
    the first looks like it worked.
    """


@dataclass
class NodeResult:
    """What a handler returns. `port` chooses which way the run continues."""

    data: dict[str, Any] = field(default_factory=dict)
    text: str = ""
    port: str = "out"


@dataclass
class NodeState:
    status: str = "pending"  # pending|running|done|failed|skipped|inactive
    data: dict[str, Any] = field(default_factory=dict)
    text: str = ""
    port: str = "out"
    error: str = ""
    attempts: int = 0


@dataclass
class RunResult:
    status: str
    nodes: dict[str, NodeState]
    variables: dict[str, Any]
    iterations: dict[str, list[dict[str, NodeState]]] = field(default_factory=dict)

    def output(self, node_id: str) -> dict[str, Any]:
        state = self.nodes.get(node_id)
        return state.data if state else {}

    def failed(self) -> list[str]:
        return [k for k, v in self.nodes.items() if v.status == "failed"]


# --------------------------------------------------------------------------- expressions

_PARAM = re.compile(r"^pipeline\(\)\.parameters\.(.+)$")
_VAR = re.compile(r"^variables\(\s*'([^']*)'\s*\)$")
_NODE = re.compile(r"^nodes\(\s*'([^']*)'\s*\)(?:\.(.+))?$")
_ITEM = re.compile(r"^item\(\)(?:\.(.+))?$")
_INDEX = re.compile(r"^index\(\)$")
_INTERP = re.compile(r"@\{([^}]*)\}")


def _walk_path(value: Any, path: str) -> Any:
    if not path:
        return value
    for part in path.split("."):
        if isinstance(value, dict):
            if part not in value:
                raise PipelineError(f"no field {part!r} in {sorted(value)[:6]}")
            value = value[part]
        elif isinstance(value, list):
            try:
                value = value[int(part)]
            except (ValueError, IndexError) as err:
                raise PipelineError(f"bad index {part!r}: {err}") from err
        else:
            raise PipelineError(f"cannot read {part!r} from {type(value).__name__}")
    return value


class _Resolver:
    """Turns `@...` references into values. Same grammar as Compass."""

    def __init__(self, parameters: dict, variables: dict, nodes: dict,
                 item: Any = None, index: int | None = None) -> None:
        self.parameters = parameters
        self.variables = variables
        self.nodes = nodes
        self.item = item
        self.index = index

    def resolve(self, value: Any) -> Any:
        if isinstance(value, dict):
            return {k: self.resolve(v) for k, v in value.items()}
        if isinstance(value, list):
            return [self.resolve(v) for v in value]
        if not isinstance(value, str):
            return value
        # `@@` is a literal at-sign, so a value that merely starts with @ can
        # still be written.
        if value.startswith("@@"):
            return value[1:]
        if value.startswith("@") and not value.startswith("@{"):
            return self._one(value[1:])
        if "@{" in value:
            return _INTERP.sub(lambda m: str(self._one(m.group(1))), value)
        return value

    def _one(self, expr: str) -> Any:
        expr = expr.strip()
        if m := _PARAM.match(expr):
            return _walk_path(self.parameters, m.group(1))
        if m := _VAR.match(expr):
            name = m.group(1)
            if name not in self.variables:
                raise PipelineError(f"no variable named {name!r}")
            return self.variables[name]
        if m := _NODE.match(expr):
            node_id = m.group(1)
            if node_id not in self.nodes:
                raise PipelineError(
                    f"node {node_id!r} has not produced a result yet"
                )
            return _walk_path(self.nodes[node_id], m.group(2) or "")
        if m := _ITEM.match(expr):
            if self.index is None:
                raise PipelineError("@item() is only available inside a loop")
            return _walk_path(self.item, m.group(1) or "")
        if _INDEX.match(expr):
            if self.index is None:
                raise PipelineError("@index() is only available inside a loop")
            return self.index
        raise PipelineError(f"unrecognised expression: {expr}")


# --------------------------------------------------------------------------- the walk


class Pipeline:
    """The exported graph, ready to run.

    `GRAPH` is filled in by the generated `graph.py`; `HANDLERS` by the
    generated `nodes.py`. Both are replaced wholesale on re-export, so custom
    handlers belong in your own code and are attached with `register`.
    """

    GRAPH: dict[str, Any] = {"nodes": [], "edges": [], "parameters": {},
                             "variables": {}, "name": "pipeline"}
    HANDLERS: dict[str, Callable[[dict, "Context"], NodeResult]] = {}

    def __init__(self) -> None:
        self._handlers = dict(self.HANDLERS)

    def register(self, node_type: str, handler: Callable) -> None:
        """Supply an implementation, or replace a generated one.

        This is how a host fills in what could not be exported — anything that
        needed Compass's workspace, its model gateway or a stored credential.
        """
        self._handlers[node_type] = handler

    # -- running ----------------------------------------------------------

    def run(self, parameters: dict[str, Any] | None = None) -> RunResult:
        graph = self.GRAPH
        params = {**graph.get("parameters", {}), **(parameters or {})}
        variables = dict(graph.get("variables", {}))
        nodes = {n["id"]: n for n in graph["nodes"]}
        states = {nid: NodeState() for nid in nodes}
        iterations: dict[str, list[dict[str, NodeState]]] = {}

        inside = set()
        for nid, node in nodes.items():
            if node.get("loop"):
                inside.update(self._body(graph, nid))

        budget = len(nodes) * 4 + 8
        while budget > 0:
            budget -= 1
            ready = self._ready(graph, nodes, states, inside)
            if not ready:
                break
            for nid in ready:
                self._run_node(graph, nodes, states, variables, params,
                               nid, iterations, inside)

        self._settle(graph, nodes, states, inside)
        status = "failed" if any(s.status == "failed" for s in states.values()) else "done"
        return RunResult(status=status, nodes=states, variables=variables,
                         iterations=iterations)

    # -- graph helpers ----------------------------------------------------

    def _body(self, graph: dict, loop_id: str) -> list[str]:
        """Nodes inside a loop: reachable from `each`, minus from `out`."""
        out_edges: dict[str, list[tuple[str, str]]] = {}
        for e in graph["edges"]:
            out_edges.setdefault(e["source"], []).append((e["target"], e.get("port", "out")))

        def reach(ports: set[str]) -> set[str]:
            seen: set[str] = set()
            stack = [t for t, p in out_edges.get(loop_id, ()) if p in ports]
            while stack:
                nid = stack.pop()
                if nid in seen or nid == loop_id:
                    continue
                seen.add(nid)
                stack.extend(t for t, _ in out_edges.get(nid, ()))
            return seen

        return sorted(reach({"each"}) - reach({"out"}))

    def _satisfied(self, edge: dict, source: NodeState) -> bool | None:
        """True to follow, False to not, None if the source is not finished."""
        if source.status in ("pending", "running"):
            return None
        when = edge.get("when", "success")
        port = edge.get("port", "out")
        if source.status == "skipped":
            return when == "skip"
        if when == "completion":
            return True
        if when == "failure":
            return source.status == "failed"
        if when == "skip":
            return False
        return source.status in ("done", "inactive") and source.port == port

    def _ready(self, graph: dict, nodes: dict, states: dict,
               inside: set[str]) -> list[str]:
        ready = []
        for nid in nodes:
            if nid in inside or states[nid].status != "pending":
                continue
            incoming = [e for e in graph["edges"] if e["target"] == nid]
            if not incoming:
                ready.append(nid)
                continue
            verdicts = [self._satisfied(e, states[e["source"]]) for e in incoming]
            if any(v is None for v in verdicts):
                continue
            if any(verdicts):
                ready.append(nid)
        return ready

    def _settle(self, graph: dict, nodes: dict, states: dict,
                inside: set[str]) -> None:
        """Anything still pending was never reachable. Say so rather than
        leaving it looking like it is about to run."""
        changed = True
        while changed:
            changed = False
            for nid in nodes:
                if nid in inside or states[nid].status != "pending":
                    continue
                incoming = [e for e in graph["edges"] if e["target"] == nid]
                if not incoming:
                    continue
                verdicts = [self._satisfied(e, states[e["source"]]) for e in incoming]
                if any(v is None for v in verdicts):
                    continue
                if all(v is False for v in verdicts):
                    states[nid].status = "skipped"
                    states[nid].text = "Not reached"
                    changed = True

    # -- one node ---------------------------------------------------------

    def _run_node(self, graph: dict, nodes: dict, states: dict,
                  variables: dict, params: dict, nid: str,
                  iterations: dict, inside: set[str],
                  scope: dict | None = None,
                  item: Any = None, index: int | None = None) -> None:
        node = nodes[nid]
        target = scope if scope is not None else states
        state = target[nid]

        # A deactivated node never runs; it reports what it was told to so the
        # branches hanging off it still exercise.
        if node.get("state") == "deactivated":
            state.status = {"success": "inactive", "failure": "failed",
                            "skip": "skipped"}.get(node.get("mark_as", "success"), "inactive")
            state.text = "Deactivated"
            return

        handler = self._handlers.get(node["type"])
        if handler is None:
            state.status = "failed"
            state.error = (
                f"No handler for {node['type']!r}. Compass could not export "
                f"this node type; supply one with "
                f"pipeline.register({node['type']!r}, fn)."
            )
            raise MissingHandler(state.error)

        # Two shapes, deliberately. The resolver sees {"data": …, "text": …}
        # because an expression is written `@nodes('id').data.field` and the
        # `.data` step has to have something to walk. A handler gets the data
        # alone, which is what it actually wants. Flattening both to the data
        # was the first version and it broke every upstream reference —
        # caught by check_export comparing against Compass's own engine.
        finished = {**states, **(scope or {})}
        visible = {k: {"data": v.data, "text": v.text}
                   for k, v in finished.items()
                   if v.status in ("done", "inactive")}
        resolver = _Resolver(params, variables, visible, item, index)

        attempts = int(node.get("retries", 0)) + 1
        interval = float(node.get("retry_interval_s", 0) or 0)
        for attempt in range(attempts):
            state.attempts = attempt + 1
            try:
                config = resolver.resolve(node.get("config", {}))
                ctx = Context(node_id=nid, variables=variables,
                              parameters=params,
                              upstream={k: v["data"] for k, v in visible.items()},
                              item=item, index=index)
                result = handler(config, ctx)
            except Exception as err:  # noqa: BLE001 — a node failure is data
                state.status = "failed"
                state.error = f"{type(err).__name__}: {err}"[:2000]
                if attempt + 1 < attempts:
                    if interval:
                        time.sleep(interval)
                    continue
                return
            state.status = "done"
            state.data = dict(result.data)
            state.text = result.text
            state.port = result.port
            state.error = ""
            if result.port == "each":
                self._run_loop(graph, nodes, states, variables, params, nid,
                               state, result, iterations, inside)
            return

    def _run_loop(self, graph: dict, nodes: dict, states: dict, variables: dict,
                  params: dict, nid: str, state: NodeState, result: NodeResult,
                  iterations: dict, inside: set[str]) -> None:
        """Run the body once per item, sequentially and in isolation."""
        body = self._body(graph, nid)
        items = list(result.data.get("items") or [])
        if not body:
            state.data = {**state.data, "results": []}
            state.port = "out"
            return

        edges = [e for e in graph["edges"]
                 if e["source"] in body and e["target"] in body]
        entry = [e["target"] for e in graph["edges"]
                 if e["source"] == nid and e.get("port") == "each"
                 and e["target"] in body]

        runs: list[dict[str, NodeState]] = []
        results: list[Any] = []
        failures = 0
        for index, item in enumerate(items):
            scope = {b: NodeState() for b in body}
            budget = len(body) + 1
            while budget > 0:
                budget -= 1
                ready = []
                for b in body:
                    if scope[b].status != "pending":
                        continue
                    incoming = [e for e in edges if e["target"] == b]
                    if not incoming:
                        if b in entry:
                            ready.append(b)
                        continue
                    verdicts = [self._satisfied(e, scope[e["source"]]) for e in incoming]
                    if any(v is None for v in verdicts):
                        continue
                    if any(verdicts):
                        ready.append(b)
                    elif all(v is False for v in verdicts):
                        scope[b].status = "skipped"
                if not ready:
                    break
                for b in ready:
                    try:
                        self._run_node(graph, nodes, states, variables, params,
                                       b, iterations, inside, scope=scope,
                                       item=item, index=index)
                    except MissingHandler:
                        raise
            runs.append(scope)
            if any(s.status == "failed" for s in scope.values()):
                failures += 1
            leaves = [b for b in body if not any(e["source"] == b for e in edges)]
            results.append({b: scope[b].data for b in leaves})

        iterations[nid] = runs
        # Roll each body node up into one state, so a caller reading
        # `result.nodes` sees something meaningful. Failure wins.
        for b in body:
            statuses = [r[b].status for r in runs]
            failed = statuses.count("failed")
            done = statuses.count("done")
            states[b].status = "failed" if failed else "done" if done else "skipped"
            states[b].text = f"{done}/{len(items)} item(s)" + (
                f", {failed} failed" if failed else "")
            states[b].error = next((r[b].error for r in runs if r[b].error), "")

        state.data = {**state.data, "results": results, "failed_items": failures}
        state.text = f"Ran {len(items)} item(s)" + (
            f", {failures} failed" if failures else "")
        state.port = "out"


@dataclass
class Context:
    """What a handler is given besides its resolved config."""

    node_id: str
    variables: dict[str, Any]
    parameters: dict[str, Any]
    upstream: dict[str, dict[str, Any]]
    item: Any = None
    index: int | None = None


def load(path: str) -> dict:
    """Read a graph from JSON, for a host that keeps it as data."""
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)
